//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Client.rc
//
#define IDD_CONNECT                     9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ClientTYPE                  130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG1                     310
#define IDD_CBrowseDirDlg               314
#define IDD_BDIR                        314
#define IDD_SPRO                        316
#define IDD_CSCR                        317
#define IDD_CInpPNameDlg                318
#define IDD_KSTR                        319
#define IDD_SPRO1                       321
#define IDD_SHOW_APP_DLG                322
#define IDD_INP_PRO_NAME_DLG            323
#define IDD_CInpAppNameDlg              324
#define IDD_INP_APP_NAME_DLG            324
#define IDB_BITMAP1                     330
#define IDB_BACKGROUND_IMAGE            330
#define IDC_CONNECT                     1001
#define IDC_IPADDRESS                   1002
#define IDC_PORT                        1003
#define IDC_MESSAGE                     1004
#define IDC_SEND                        1005
#define IDC_BUTTON1                     1006
#define IDC_BN_CONN                     1007
#define IDC_BN_SAPP                     1008
#define IDC_BN_SPRO                     1009
#define IDC_BUTTON2                     1009
#define IDC_BN_KSTR_UNHK                1009
#define IDC_BN_CSCR                     1010
#define IDC_BN_KSTR                     1011
#define IDC_BN_BDIR                     1012
#define IDC_EDIT_KEYSTROKE              1012
#define IDC_IMAGE                       1013
#define IDC_BN_KSTR_HOOK                1013
#define IDC_LIST_DIR                    1018
#define IDC_LIST_PRO                    1019
#define ID_KILL_BTN                     1020
#define ID_START_PRO                    1021
#define IDC_EDIT1                       1022
#define IDC_INP_PRO                     1022
#define IDC_INP_NAME_PRO                1022
#define IDC_INP_NAME_APP                1022
#define IDC_EDIT_PATH                   1024
#define IDC_BTN_BACK                    1027
#define ID_KILL_APP_BTN                 1032
#define ID_START_APP_BTN                1033
#define IDC_LIST_APP                    1036
#define IDC_BTN_START                   1037
#define ID_BTN_START                    1038
#define ID_CONNECT_CONNECTTOSERVER      32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           325
#endif
#endif
